env:
  browser: true
  es2021: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {}
overrides: [
  {
    files: ['*.js'],
    rules: {
      no-unused-vars: 'off',
      no-undef: 'off'
    }
  }
]
